### ISSUE TITLE
Can't get <C-x><C-t> completion to work

### ISSUE THREAD

**Issue by trevordmiller** [KeyboardFire/vim-minisnip#21]
I see that there is a built in completion keybinding [in the docs](https://github.com/joereynolds/vim-minisnip/blob/eca1473aae66d1fc8a68c2b139ff3e79a7696796/doc/minisnip.txt#L43-L46) and [in the plugin's code](https://github.com/joereynolds/vim-minisnip/blob/eca1473aae66d1fc8a68c2b139ff3e79a7696796/plugin/minisnip.vim#L35-L39). But whenever I use ctrl + x then ctrl + t I get `'thesaurus' option is empty`. My snippets do work with `foo<Tab>` though. Is some other config needed to get `<C-x><C-t>` to complete the list of snippets available?

I don't have any minisnip or completion specific config in [my .vimrc](https://github.com/trevordmiller/dotfiles/blob/master/files/.vimrc). I'd like to be able to list out all my available minisnip snippets to select them as other built-in Vim completion works; for example, with ctrl + n:
![image](https://user-images.githubusercontent.com/5497885/36345935-d94bf744-13f1-11e8-979d-3427229b4493.png)

**Comment by arp242** [comment]
Which repo are you using? KeyboardFire/vim-minisnip or joereynolds/vim-minisnip? Support for completion is only in the latter.

**Comment by trevordmiller** [comment]
My bad, I didn’t even notice that was a fork :facepalm:
