### ISSUE TITLE
let g:minisnip_dir doesn't work with ~/ user path

### ISSUE THREAD

**Issue by trevordmiller** [KeyboardFire/vim-minisnip#5]
First off, thanks for a great plugin! I've been looking for a lightweight alternative to the bloated snippet plugins and this is fantastic :)

I'm able to use minisnip with the default `~/.vim/minisnip` directory, but not with something like:
`let g:minisnip_dir = '~/snippets'`. [I have other `~/` rules in my .vimrc](https://github.com/trevordmiller/settings/blob/master/dotfiles/.vimrc#L63-L65) that work ok, not sure what the difference would be here.

Thanks again for your great work!

**Comment by tckmn** [comment]
@trevordmiller Thanks for the feedback; I'm glad you found my plugin useful! :)
