### ISSUE TITLE
Mapping key already exists.

### ISSUE THREAD

**Issue by emaniacs** [KeyboardFire/vim-minisnip#7]
I got an error because of mapping key was taken.
```
Error detected while processing .vim/bundle/vim-minisnip/plugin/vim-minisnip.vim:
line  119:
E227: mapping already exists for ^I
```

I install plugin with https://github.com/junegunn/vim-plug
This is my vimrc, https://github.com/emaniacs/my-dot-config/blob/master/dot-vimrc

Thanks :)

**Comment by tckmn** [comment]
The error message seems pretty self-explanatory—your tab key is already mapped to something else (presumably by supertab or some other plugin; you can use `:imap <tab>` to find out). See `:h 'g:minisnip_trigger'`.

**Comment by emaniacs** [comment]
yes, i understand about the error message,i use supertab.
Actually, i still wanna use <Tab> for this snippet,
and i think, i need to configured at supertab.

btw, thanks :)
